---
    - name: Create EC2 keypair for nodes
      ec2_key:
        name: "{{ aws_keypair }}"
        key_material: "{{ lookup('file', '{{ ansible_env.HOME }}/.ssh/id_rsa.pub') }}"
        region: "{{ aws_region }}"
        state: "{{ aws_state | default('present') }}"
      delegate_to: localhost
